ALTER TABLE FLIGHT 
DROP COLUMN FLIGHT_DURATION;

ALTER TABLE FLIGHT
ALTER COLUMN DEPARTURE_DATE TYPE TIMESTAMP WITHOUT TIME ZONE
USING DEPARTURE_DATE::TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE FLIGHT
ALTER COLUMN ARRIVAL_DATE TYPE TIMESTAMP WITHOUT TIME ZONE
USING ARRIVAL_DATE::TIMESTAMP WITHOUT TIME ZONE;