CREATE TABLE IF NOT EXISTS ROBOT_MODEL_CATALOG (
    ROBOT_MODEL VARCHAR(32) PRIMARY KEY,
    FUNCTION VARCHAR(128) NOT NULL,
    WEIGHT SMALLINT NOT NULL
);

ALTER TABLE ROBOT
ADD CONSTRAINT fk_robot_model
FOREIGN KEY (robot_model) REFERENCES ROBOT_MODEL_CATALOG (robot_model);

ALTER TABLE ROBOT
DROP COLUMN FUNCTION;

ALTER TABLE ROBOT
DROP COLUMN WEIGHT;