SELECT
	P.NAME,
	F.DEPARTURE_POINT,
	F.DEPARTURE_DATE,
	F.PLACE_OF_ARRIVAL,
	F.ARRIVAL_DATE,
	F.SPACESHIP_NAME
FROM PASSENGER P
	JOIN FULL_HEALTH_ANALYSIS_RESULT FHAR ON P.ANALYSIS_ID = FHAR.ANALYSIS_ID
	JOIN PASSENGER_FLIGHT PF ON PF.PASSENGER_ID = P.PASSENGER_ID
	JOIN FLIGHT F ON PF.FLIGHT_ID = F.FLIGHT_ID
WHERE FHAR.ALLOWED_TO_FLY = TRUE;