SELECT
	P.NAME,
	FHAR.EXPIRE_BY,
	FHAR.GRANTED_BY,
	I.EXPIRE_BY,
	I.COMPANY_GRANTED_BY
FROM PASSENGER P
JOIN FULL_HEALTH_ANALYSIS_RESULT FHAR ON P.ANALYSIS_ID = FHAR.ANALYSIS_ID
JOIN INSURANCE I ON P.INSURANCE_ID = I.INSURANCE_ID