INSERT INTO FULL_HEALTH_ANALYSIS_RESULT(EXPIRE_BY, ALLOWED_TO_FLY, GRANTED_BY)
VALUES
	('2027-10-11', TRUE, 'Ministry of Health of Ukraine');

INSERT INTO INSURANCE(EXPIRE_BY, COMPANY_GRANTED_BY)
VALUES
	('2035-05-17', 'USC IP');

INSERT INTO CONTAINER(MAX_WEIGHT)
VALUES
	(2000);

INSERT INTO PASSENGER(NAME, PHONE_NUMBER, EMAIL,  ANALYSIS_ID, INSURANCE_ID)
VALUES 
	('Alice Baker', '+447448932715', 'aliceCookie@gmail.com', 1, 1);

INSERT INTO BAGGAGE(MAX_WEIGHT, PASSENGER_ID, CONTAINER_ID)
VALUES
	(150, 1, 1);

INSERT INTO SPACESHIP(SPACESHIP_NAME, DATE_OF_MANUFACTURE, PASSENGER_CAPACITY, CONTAINERS_CAPACITY)
VALUES
	('Kadenyuk 1','2025-11-01', 12, 10);

INSERT INTO ROBOT(ROBOT_MODEL, FUNCTION, WEIGHT, CONTAINER_ID)
VALUES
	('SR-009', 'Science helper', 220, 1);

INSERT INTO FLIGHT(DEPARTURE_POINT, DEPARTURE_DATE, PLACE_OF_ARRIVAL, ARRIVAL_DATE, FLIGHT_DURATION, SPACESHIP_NAME)
VALUES
	('SaxaVord Spaceport', '2026-8-3', 'PMF Columbus', '2026-12-3', '4 days', 'Kadenyuk 1');

INSERT INTO PASSENGER_FLIGHT(PASSENGER_ID, FLIGHT_ID)
VALUES
	(1, 1);

INSERT INTO CONTAINER_FLIGHT(CONTAINER_ID, FLIGHT_ID)
VALUES
	(1, 1);