CREATE TABLE IF NOT EXISTS CONTAINER (
    CONTAINER_ID SERIAL PRIMARY KEY,
    MAX_WEIGHT INT NOT NULL CHECK (MAX_WEIGHT <= 10000)
);

CREATE TABLE IF NOT EXISTS SPACESHIP (
    SPACESHIP_NAME VARCHAR(64) PRIMARY KEY,
    DATE_OF_MANUFACTURE DATE NOT NULL,
    PASSENGER_CAPACITY SMALLINT NOT NULL,
    CONTAINERS_CAPACITY SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS FLIGHT (
    FLIGHT_ID SERIAL PRIMARY KEY,
    DEPARTURE_POINT VARCHAR(32) NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    PLACE_OF_ARRIVAL VARCHAR(32) NOT NULL,
    ARRIVAL_DATE DATE NOT NULL,
    FLIGHT_DURATION VARCHAR(32) NOT NULL,
    SPACESHIP_NAME VARCHAR(64) REFERENCES SPACESHIP (SPACESHIP_NAME)
);

CREATE TABLE IF NOT EXISTS PASSENGER (
    PASSENGER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    PHONE_NUMBER VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS BAGGAGE (
    BAGGAGE_ID SERIAL PRIMARY KEY,
    WEIGHT SMALLINT NOT NULL,
    PASSENGER_ID INT REFERENCES PASSENGER (PASSENGER_ID),
    CONTAINER_ID INT NOT NULL REFERENCES CONTAINER (CONTAINER_ID)
);

CREATE TABLE IF NOT EXISTS ROBOT (
    ROBOT_ID SERIAL PRIMARY KEY,
    ROBOT_MODEL VARCHAR(32) NOT NULL,
    FUNCTION VARCHAR(128) NOT NULL,
    WEIGHT SMALLINT NOT NULL,
    CONTAINER_ID INT NOT NULL REFERENCES CONTAINER (CONTAINER_ID)
);

CREATE TABLE IF NOT EXISTS FULL_HEALTH_ANALYSIS_RESULT (
    ANALYSIS_ID SERIAL PRIMARY KEY,
    EXPIRE_BY DATE NOT NULL,
    ALLOWED_TO_FLY BOOL NOT NULL,
    GRANTED_BY VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSURANCE (
    INSURANCE_ID SERIAL PRIMARY KEY,
    EXPIRE_BY DATE NOT NULL,
    COMPANY_GRANTED_BY VARCHAR(32) NOT NULL
);

-- FK
ALTER TABLE PASSENGER
ADD COLUMN ANALYSIS_ID INT UNIQUE REFERENCES FULL_HEALTH_ANALYSIS_RESULT(ANALYSIS_ID);
 
ALTER TABLE PASSENGER
ADD COLUMN INSURANCE_ID INT UNIQUE REFERENCES INSURANCE(INSURANCE_ID);

ALTER TABLE FULL_HEALTH_ANALYSIS_RESULT
ADD COLUMN PASSENGER_ID INT UNIQUE REFERENCES PASSENGER(PASSENGER_ID);

ALTER TABLE INSURANCE
ADD COLUMN PASSENGER_ID INT UNIQUE REFERENCES PASSENGER(PASSENGER_ID);

-- Relations
CREATE TABLE IF NOT EXISTS PASSENGER_FLIGHT (
    PASSENGER_ID INT NOT NULL REFERENCES PASSENGER (PASSENGER_ID),
    FLIGHT_ID INT NOT NULL REFERENCES FLIGHT (FLIGHT_ID),
    PRIMARY KEY (PASSENGER_ID, FLIGHT_ID)
);

CREATE TABLE IF NOT EXISTS CONTAINER_FLIGHT (
    CONTAINER_ID INT NOT NULL REFERENCES CONTAINER (CONTAINER_ID),
    FLIGHT_ID INT NOT NULL REFERENCES FLIGHT (FLIGHT_ID),
    PRIMARY KEY (CONTAINER_ID, FLIGHT_ID)
);

CREATE TABLE IF NOT EXISTS CONTAINER_ITEMS (
    CONTAINER_ITEM_ID SERIAL PRIMARY KEY,
    CONTAINER_ID INT NOT NULL REFERENCES CONTAINER (CONTAINER_ID),
    BAGGAGE_ID INT REFERENCES BAGGAGE (BAGGAGE_ID),
    ROBOT_ID INT REFERENCES ROBOT (ROBOT_ID),
    CHECK (
        (BAGGAGE_ID IS NOT NULL AND ROBOT_ID IS NULL) OR
        (BAGGAGE_ID IS NULL AND ROBOT_ID IS NOT NULL)
    )
);
