// <auto-generated />
using System;
using Fly_Me_to_the_Moon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fly_Me_to_the_Moon.Migrations
{
    [DbContext(typeof(SpaceFlightContext))]
    [Migration("20251217231855_AddRawVersiontoContext")]
    partial class AddRawVersiontoContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Baggage", b =>
                {
                    b.Property<int>("BaggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BaggageId"));

                    b.Property<int?>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("integer");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BaggageId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("baggage", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Container", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContainerId"));

                    b.Property<int>("MaxWeight")
                        .HasColumnType("integer");

                    b.HasKey("ContainerId");

                    b.ToTable("container", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.ContainerFlight", b =>
                {
                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("ContainerId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("container_flight", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightId"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfArrival")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceshipName")
                        .HasColumnType("text");

                    b.HasKey("FlightId");

                    b.HasIndex("ArrivalDate")
                        .HasDatabaseName("IX_Flight_ArrivalDate");

                    b.HasIndex("DepartureDate")
                        .HasDatabaseName("IX_Flight_DepartureDate");

                    b.HasIndex("SpaceshipName")
                        .HasDatabaseName("IX_Flight_SpaceshipName");

                    b.ToTable("flight", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.FullHealthAnalysisResult", b =>
                {
                    b.Property<int>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalysisId"));

                    b.Property<bool>("AllowedToFly")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpireBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("AnalysisId");

                    b.HasIndex("AllowedToFly")
                        .HasDatabaseName("IX_FullHealthAnalysisResult_AllowedToFly");

                    b.ToTable("full_health_analysis_result", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InsuranceId"));

                    b.Property<string>("CompanyGrantedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("InsuranceId");

                    b.ToTable("insurance", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("PassengerId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.HasIndex("InsuranceId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Passenger_Name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Passenger_PhoneNumber");

                    b.ToTable("passenger", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.PassengerFlight", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("PassengerId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("passenger_flight", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Robot", b =>
                {
                    b.Property<int>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RobotId"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("RobotModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RobotId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("RobotModel")
                        .HasDatabaseName("IX_Robot_RobotModel");

                    b.ToTable("robot", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.RobotModelCatalog", b =>
                {
                    b.Property<string>("RobotModel")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("RobotModel");

                    b.ToTable("robot_model_catalog", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.ServiceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceshipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("SpaceshipName")
                        .HasDatabaseName("IX_ServiceLog_SpaceshipName");

                    b.ToTable("service_log", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Spaceship", b =>
                {
                    b.Property<string>("SpaceshipName")
                        .HasColumnType("text");

                    b.Property<int>("ContainersCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("integer");

                    b.HasKey("SpaceshipName");

                    b.HasIndex("SpaceshipName")
                        .IsUnique()
                        .HasDatabaseName("IX_Spaceship_Name");

                    b.ToTable("spaceship", (string)null);
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Baggage", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Container", "Container")
                        .WithMany("Baggage")
                        .HasForeignKey("ContainerId");

                    b.HasOne("Fly_Me_to_the_Moon.Models.Passenger", "Passenger")
                        .WithOne("Baggage")
                        .HasForeignKey("Fly_Me_to_the_Moon.Models.Baggage", "PassengerId");

                    b.Navigation("Container");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.ContainerFlight", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Container", "Container")
                        .WithMany("ContainerFlight")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fly_Me_to_the_Moon.Models.Flight", "Flight")
                        .WithMany("ContainerFlight")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Flight", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Spaceship", "Spaceship")
                        .WithMany("Flight")
                        .HasForeignKey("SpaceshipName");

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Passenger", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.FullHealthAnalysisResult", "FullHealthAnalysisResult")
                        .WithOne("Passenger")
                        .HasForeignKey("Fly_Me_to_the_Moon.Models.Passenger", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fly_Me_to_the_Moon.Models.Insurance", "Insurance")
                        .WithOne("Passenger")
                        .HasForeignKey("Fly_Me_to_the_Moon.Models.Passenger", "InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FullHealthAnalysisResult");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.PassengerFlight", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Flight", "Flight")
                        .WithMany("PassengerFlight")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fly_Me_to_the_Moon.Models.Passenger", "Passenger")
                        .WithMany("PassengerFlight")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Robot", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Container", "Container")
                        .WithMany("Robot")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fly_Me_to_the_Moon.Models.RobotModelCatalog", "RobotModelCatalog")
                        .WithMany("Robot")
                        .HasForeignKey("RobotModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("RobotModelCatalog");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.ServiceLog", b =>
                {
                    b.HasOne("Fly_Me_to_the_Moon.Models.Spaceship", "Spaceship")
                        .WithMany("ServiceLog")
                        .HasForeignKey("SpaceshipName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Container", b =>
                {
                    b.Navigation("Baggage");

                    b.Navigation("ContainerFlight");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Flight", b =>
                {
                    b.Navigation("ContainerFlight");

                    b.Navigation("PassengerFlight");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.FullHealthAnalysisResult", b =>
                {
                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Insurance", b =>
                {
                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Passenger", b =>
                {
                    b.Navigation("Baggage");

                    b.Navigation("PassengerFlight");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.RobotModelCatalog", b =>
                {
                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Fly_Me_to_the_Moon.Models.Spaceship", b =>
                {
                    b.Navigation("Flight");

                    b.Navigation("ServiceLog");
                });
#pragma warning restore 612, 618
        }
    }
}
